paths:
    migrations: %%PHINX_CONFIG_DIR%%/../database/migrations

environments:
    default_migration_table: phinxlog
    default_database: development


    development:
        adapter: sqlite
        name: %%PHINX_CONFIG_DIR%%/../database/development.sqlite
